 const defects = [
  {
    id: 1753,
    title: "new tests",
    assignee: "Reshu Kolhe",
    status: "Assigned",
    stage: "Assigned",
    environment: "DEV",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Piyush Shahu",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1101,
    title: "IQ Agent - Unable to Download Test Set xnjxndjncj",
    assignee: "Dipesh Bhattarai hiebgbejgbbgu",
    status: "Rejected",
    stage: "Open",
    environment: "BCBSKS PROD",
    severity: "Major Problem",
    tag: "-",
    source: "Regression",
    defectOwner: "Khushi Bopche",
    defectRelease: "InfoQA release 2026.04",
  },
  {
    id: 1739,
    title: "Allow log and json attachment",
    assignee: "Shweta Tarate",
    status: "Assigned",
    stage: "Assigned",
    environment: "BCBSKS PROD",
    severity: "Crash/Data Loss",
    tag: "APP",
    source: "Regression",
    defectOwner: "Abhishek Chakole",
    defectRelease: "InfoQA Release 1",
  },
  {
    id: 1801,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Zinel Bhagdeo",
    defectRelease: "InfoQA Release 2026.08",
  },
  {
    id: 9801,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Roshani Sahu",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1271,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Dheeraj Manwani",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1791,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Reshu Kolhe",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 5801,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Pankaj Patle ",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1831,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "User Story",
    defectOwner: "yash gupta",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 2801,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "User Story",
    defectOwner: "xyz",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1901,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "User Story",
    defectOwner: "Piyush Shahu",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1851,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Piyush Shahu",
    defectRelease: "InfoQA Release 2026.05",
  },
  {
    id: 1834,
    title: "Login Issue",
    assignee: "Rahul Sharma",
    status: "Assigned",
    stage: "Open",
    environment: "QA",
    severity: "Major Problem",
    tag: "APP",
    source: "Regression",
    defectOwner: "Piyush Shahu",
    defectRelease: "InfoQA Release 2026.05",
  },
];
module.exports=defects;
